name: Deploy Nginx on Self-hosted Runner

on:
  push:
    branches:
      - main  # Trigger on push to main branch 
    paths:
      - '.github/workflows/AwsInstanceRunningJob.yml'

jobs:
  deploy-nginx:
    runs-on: self-hosted # Ensure this matches the label of your self-hosted runner
    # to run on a specific self-hosted need to add a label and then >> runs-on: [self-hosted, linux-large-ram]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx

    - name: Start Nginx
      run: sudo systemctl start nginx

    - name: Enable Nginx to start on boot
      run: sudo systemctl enable nginx

    - name: Print the status of Nginx
      run: sudo systemctl status nginx | cat # Using 'cat' to avoid failing due to 'systemctl' exit codes

    - name: Sleep for 20 seconds
      run: sleep 20

    - name: Stop Nginx
      run: sudo systemctl stop nginx
