name: CI/CD AWS
env:
  BUCKET_NAME: "newiftnew"
  APP_NAME: "myAPP"
  PACKAGE_NAME: "my_app_ver-${{ github.sha }}.zip"
  AWS_REGION: "us-east-1"
  
on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
    paths:
      - '.github/workflows/s3Bucket.yml'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: AWSCli version
        run: aws --version

      # Runs a set of commands using the runners shell
      - name: configure AWS cred
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1
      
      - name: Create package
        run: zip -r ${{ env.PACKAGE_NAME}} ./ -x *.git*

      - name: Send Package
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.BUCKET_NAME }}/
